syntax = "proto3";

package vn.com.routex.hub.grpc;

option java_multiple_files = true;
option java_package = "vn.com.routex.hub.grpc";
option java_outer_classname = "BookingServiceProto";

service BookingGrpcService {
  rpc FetchBookingPaymentContext (FetchBookingPaymentContextRequest) returns (FetchBookingPaymentContextResponse);
}

message BookingRequestContext {
  string request_id = 1;
  string request_date_time = 2;
  string channel = 3;
}

message FetchBookingPaymentContextRequest {
  string booking_code = 1;
  BookingRequestContext context = 2;
}

message FetchBookingPaymentContextResponse {
  string booking_id = 1;
  string booking_code = 2;
  string total_amount = 3;
  string currency = 4;
  string booking_status = 5;
  string hold_until = 6;
}
